### ISSUE TITLE
VSCode F5 run/debug?

### ISSUE THREAD

**Issue by ssnseawolf** [pycom/pymakr-vsc#10]
Is it possible to F5 debug (or even just stop and run with no debugger attached) in VSCode?

The REPL is fantastic, but hitting `CTRL+SHIFT+C, CTRL+SHIFT+R` every time is a bit tedious. Or perhaps it's there and I don't know the proper launch.json config settings?

**Comment by RalphHogenbirk** [comment]
Hi @ssnseawolf, no there is no debugger for micropython at this time. You'll have to use prints and perhaps time.sleep() to figure out what's going wrong in your file. Whenever there is one available, we'll also try to intergrate it into Pymakr ofcourse. Until that time that won't work.

Fastest way tot test is using the 'run' or 'upload' features of Pymakr. Crl+shift+c to connect shouldn't be needed every time, if you keep your board connected over USB.
