### ISSUE TITLE
Not working with July 2018 release

### ISSUE THREAD

**Issue by tahouse** [pycom/pymakr-vsc#11]
My VS Code auto-updated to the July 2018 release, Version 1.26.0 (1.26.0). Since then, the pymakr extension has stopped working. My system is running MacOS High Sierra 10.13.6 and my installed node-js is v6.11.2.

I've tried reinstalling the pymakr extension, then restarting VS Code. I've tried disabling, restarting, reloading, and even restarting my Macbook, etc etc. but continue to errors when trying to use any of the pymakr commands. These all worked just fine previous to the vs code update. For instance, when selecting typical commands, I get an an saying "command 'pymakr.projectSettings' not found" or "command 'pymakr.help' not found".

I've tested the issue by downgrading to the June 2018 VS Code release and pymakr works fine again, but stops working as soon as I update to July 2018.

I'd like to be able to update VS Code going forward while still using your extension -- if there is something I can do to help debug let me know?

**Comment by gizmocuz** [comment]
Experiencing the same issue here with VSCode version 1.27.0-insider

Working:
June 2018 release is version 1.25.1
NodeJS LTS 8.11.4

Would be great to use the latest VSCode

**Comment by gizmocuz** [comment]
When compiling and launching in debug mode, i get the following error:

Activating extension 'pycom.pymakr' failed: The module '\\?\E:\Projects\PyCom.io\pymakr-vsc-master\precompiles\serialport-win\build\Release\serialport.node' was compiled against a different Node.js version using NODE_MODULE_VERSION 54. This version of Node.js requires NODE_MODULE_VERSION 57. Please try re-compiling or re-installing the module (for instance, using `npm rebuild` or `npm install`)..

it has to do with the precompiles in this project.

Can this somehow be avoided and use the standard serialport npm ?

**Comment by RalphHogenbirk** [comment]
Hi, I'm aware of this issue, but due to the holidays we haven't been able to fix and update vscode yet. Like @gizmocuz says it's to do with the precompiled seriaport lib.

In a little more than a week I'll be able to fix and release the patch. Untill then, try downgrading vscode if that's not an issue for you. Sorry for the inconvenience.

**Comment by polarapfel** [comment]
I'm on VS Code 1.26.1, I tried a fresh install of pymakr. None of the commands from the palette work then, they all fail like this _command 'pymakr.globalSettings' not found_.

**Comment by tobz-nz** [comment]
@polarapfel As @RalphHogenbirk has noted the vscode plugin is currently broken. You either have to downgrade vscode, or use Atom in the meantime while they fix it.

The easier option for me was just use Atom.

**Comment by RalphHogenbirk** [comment]
Sorry for the delay, we had some trouble getting the terminal to work properly in windows on the new vscode versions. Holidays and an office move also didn't help.

Pymakr v1.0.2 has now been released and should be working with all the latest versions of VSCode (v1.27.1 right now)

Let me know if all of your issues are solved now

**Comment by tahouse** [comment]
Works for me now, thank you for the effort!

**Comment by elektrobil** [comment]
I have still same error `:command pymakr.connect not found`
Im using Opensuse Tumbleweed on VSCODE 
can you help for this issue ?

**Comment by wybiral** [comment]
I'm getting a similar error message on Ubuntu Bionic with VSCode 1.27.2.

The developer tools error is:
```
Activating extension `pycom.pymakr` failed:  The module '/home/davy/.vscode/extensions/pycom.pymakr-1.0.2/precompiles/serialport-linux/build/Release/serialport.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 54. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
```

**Comment by RalphHogenbirk** [comment]
Sorry about that @wybiral, the serialport precompile for linux doesn't seem to be updated properly. I compiled it to a slightly older vscode by accident. Will fix it and include it in an update for you. Expect it on monday. 

If you need it this weekend, try running ```npm install``` in the pymakr extension folder, which might fix it for you right now. Otherwise downgrade vscode to 1.25, or fall back to Atom for this weekend. Sorry for the inconvenience.

**Comment by tenager** [comment]
I can't get it working on Ubuntu 18.04.1 LTS using vscode 1.29. The nodjs version is v8.10. Listing the serial ports works fine with Pymakr, but trying to connect to the serial port doesn't work. I tried to downgrade to vscode 1.25 and 1.26, but didnt succeed.

**Comment by RalphHogenbirk** [comment]
Hi @tenager, That might be a permission issue. Try the dialout command on the bottom of the readme file here: https://github.com/pycom/pymakr-atom/#cannot-connect-to-pycom-on-linux

**Comment by tenager** [comment]
Hi, I just tested that but didn't solve the problem. There is  X sign before Pycom Console and the connection stacks with the message "Connecting on /dev/ttyUSB0..."

**Comment by tenager** [comment]
without sudo, screen command terminates. But, with sudo, screen seems to work.

**Comment by tenager** [comment]
Ah...just rebooted my device, problem is solved! Pymakr works with vscode on Ubuntu 18.04. Thanks @RalphHogenbirk

**Comment by RalphHogenbirk** [comment]
@tenager ok, good to hear! Turning something off and on again is still the solution sometimes

**Comment by GurraE** [comment]
I'm using Win10 & VS Code 1.33.1. 
I have installed PyMakr VSC 1.10 & my installed Node Js version is 10.15.3
The PyMakr extension installs, but no icons appear at bottom left and when trying to use command: 
Pymakr Global Setting
I get the message:
command pymakr.globalsettings not found
 
Is this still a problem ??

**Comment by Othellosos** [comment]
Confirmed, I tried to use exactly the same setup & get the same message yesterday.
Did someone open a new thread?

**Comment by choeffer** [comment]
I created a new bug report for this https://github.com/pycom/pymakr-vsc/issues/45

**Comment by RalphHogenbirk** [comment]
You're correct guys, on a lot of win10 PC's it's not working correctly at the moment. An issue with the install script. Check issue https://github.com/pycom/pymakr-vsc/issues/42 for more info. Also note this command that temporarily solves the issue: https://github.com/pycom/pymakr-vsc/issues/42#issuecomment-490413721

**Comment by choeffer** [comment]
https://github.com/pycom/pymakr-vsc/issues/45 is about that it is not working with Linux as well, so not at Win10 specific problem.

**Comment by RalphHogenbirk** [comment]
@choeffer I see, I must have read over that line by accident. Still it's probably the same issue, it makes sense that it would also occur on linux. It just happens more often on windows because the electron-rebuild almost never works on windows without effort, but is more likely to work on linux. (The issue we're talking about only occurs in the case when the electron-rebuild script fails)

**Comment by choeffer** [comment]
@RalphHogenbirk no problem, I just wanted to mention so that it is clear that there mirght be another/different issue with Linux.
