### ISSUE TITLE
Pymakr does not show in 'Code - OSS' version of VS Code

### ISSUE THREAD

**Issue by GregTheHun** [pycom/pymakr-vsc#133]
## What are the steps to reproduce this issue?
1. Open VS Code (Code - OSS version on Linux [Manjaro])
2. Try to search in Extensions tab for 'Pymakr'

## What happens?
Doesn't appear for installation

## What were you expecting to happen?
Have Pymakr appear as an installation option for the Code - OSS version of VS Code

## Any logs, error output, etc?
None, unfortunately it searches, but nothing appears

## What versions of software are you using?

**Operating system:**
Manjaro
kernel: 5.10.26-1
DISTRIB_RELEASE=21.0.1
DISTRIB_CODENAME=Ornara

**VSCode version:**
Code - OSS
Ver. 1.54.3

**Pymakr version:**
None appears

**Comment by GregTheHun** [comment]
If it helps (maybe not much), but here's a screenshot:

![Screenshot_2021-04-16_09-26-39](https://user-images.githubusercontent.com/19254816/115039266-eab55480-9e95-11eb-8168-37c3c619f354.png)

**Comment by elmasria** [comment]
@GregTheHun 

Please can you check again, I just double-checked from my side and I can see pymakr on VSC.

Thank you.

**Comment by GregTheHun** [comment]
Correct, it is on VS Code one from Microsoft, but there's also an open source version you can find on many Linux distrobutions titled, "Code - OSS", that one still doesn't present it.

**Comment by elmasria** [comment]
Hello @GregTheHun,

Sorry for this delay. I was checking and I saw that the Marketplace of **VSCode** is not the same as **Code - OSS**, or at least that what I have understood. 

What I did is that I create a new Release where you can have access to the `vsix` extension so you can install **Pymkr** manually. 

NB: if you have some reference on how we should add **Pymakr** to that marketplace, I will appreciate your support.

Reference: https://github.com/microsoft/vscode/wiki/Differences-between-the-repository-and-Visual-Studio-Code

![image](https://user-images.githubusercontent.com/12611535/117306293-d9051280-ae7f-11eb-86ca-4f0adca85053.png)

Hope the above is useful. Have a nice day,

Best Regards,
Ahmad EL Masri
