### ISSUE TITLE
Pymakr  v1.1.11 stop working with new version of VSC 1.56.0.

### ISSUE THREAD

**Issue by livius2** [pycom/pymakr-vsc#135]
Pymakr  v1.1.11 stop working with new version of VSC 1.56.0.

VSC Version: 1.56.0 (user setup)
Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
Date: 2021-05-04T22:09:06.405Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19041

Pymakr version: v1.1.11

There was an error with your serialport module, Pymakr will likely not work properly. 
Please try to install again or report an issue on our github (see developer console for details)
reinstalled but did not help.

**Comment by elmasria** [comment]
@livius2, Thanks for reporting this I will take a look.

**Comment by tibuski** [comment]
Same issue since this morning and Visual Studio Code update 1.56.0

**Comment by elmasria** [comment]
@livius2 and @tibuski We published new version 1.1.12. Let me know if you have any issues with the new version. Thank you

**Comment by tibuski** [comment]
Wow !

What a service :) Issue at 8am and solved at 2pm !

Thank you very much !

**Comment by livius2** [comment]
Yes, it is fixed, thx

**Comment by elmasria** [comment]
Great, I am happy that it has been fixed for you Thanks for the feedback. I will close this issue.
