### ISSUE TITLE
 There was an error with your serialport module, Pymakr will likely not work properly. Please try to install again or report an issue on our github (see developer console for details)

### ISSUE THREAD

**Issue by antifm** [pycom/pymakr-vsc#147]
Having this error running on Pymakr v1.1.12 on vscode version1.59.

How can I fix this?

Thanks

**Comment by William04A** [comment]
@antifm I am not sure when PyCom plans to fix this, because in the meantime the solution is to downgrade Visual Studio Code. See this issue which reports the same thing: https://github.com/pycom/pymakr-vsc/issues/144

**Comment by AlexanderPilhar** [comment]
Also, have a look at my solution [installing VS Code Portable in compatible version for PyMakr](https://github.com/pycom/pymakr-vsc/issues/145#issuecomment-899455606)!

**Comment by antifm** [comment]
@William04A That sucks. Thanks for the redirect!
 @AlexanderPilhar, thank you for the solution. Got it working through the portable mode! Greatly appreciated!

Cheers to the both of you

**Comment by jakobrosenberg** [comment]
Closing in favor of https://github.com/pycom/pymakr-vsc/issues/119
