### ISSUE TITLE
error with your serialport module, Pymakr will likely not work properly

### ISSUE THREAD

**Issue by PrimeTime416** [pycom/pymakr-vsc#149]
Hello Pymakr stopped working for me, please note I tried it both under linux and Windows 10 (VM).  If you open VSCode  you will get a message saying:

_There was an error with your serialport module, Pymakr will likely not work properly. Please try to install again or report an issue on our github (see developer console for details)_

I have never had an issue with Pymakr until now, please help, thanks all.

**Comment by tronto** [comment]
I'm having the same issuse. Running VS code 1.59.1 on mac 10.15.7

**Comment by schulte2003** [comment]
I have the same issue with Mac OS 11.5.2, VS Code 1.58.2 on a M1 Chip

**Comment by anomaly256** [comment]
Same with vscode 1.59.1 and pymakr extension v1.1.12 on an amd64 debian 10 linux

**Comment by swordfishBob** [comment]
Me also, Win 10, VS Code.

**Comment by PrimeTime416** [comment]
I am not sure if this is related to the vsCode trust verification? the code looked, looks like it use node.js serialport? I tested serial by it self and I can communicate to the ESP32:


```
const SerialPort = require('serialport');

const comX = '/dev/ttyUSB0';
const Readline = SerialPort.parsers.Readline;
const port = new SerialPort(comX, {baudRate: 115200});
const parser = new Readline();
port.pipe(parser);
parser.on('data', (dataX)=>{
    console.log(dataX);
});
port.write('\x03\n\r'); //<CTRL-C>

process.stdout.write('hello world');

process.stdin.on('data',(dataX)=>{
    dataX = dataX.toString().trim();
    port.write(`${dataX}\r\n`);
});
```

**Comment by jakobrosenberg** [comment]
Closing in favor of https://github.com/pycom/pymakr-vsc/issues/119
