### ISSUE TITLE
Not working in VsCode on Mac

### ISSUE THREAD

**Issue by diasrobson** [pycom/pymakr-vsc#151]
**What are the steps to reproduce this issue?**
1.have Ran it on VSCode Version 1.33.1 (1.33.1) and  Version: 1.59.1 (Universal)
2. Node version v14.17.5

**What happens?**
**When installing Pymakr on Version: 1.59.1  i get the following error after install has completed and any time i reboot VsCode** 
T'here was an error with your serialport module, Pymakr will likely not work properly. Please try to install again or report an issue on our github (see developer console for details"

**when running in Version 1.33.1 (1.33.1) I get this in the Debug window** 
dyld: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/robson/.vscode/extensions/pycom.pymakr-1.1.6/node_modules/@serialport/bindings/lib/binding/node-v64-darwin-x64/bindings.node
  Expected in: flat namespace

**Operating system:**
Mac OS Big Sur V11.5.2

**VSCode version:**
VSCode Version 1.33.1 (1.33.1) and  Version: 1.59.1 (Universal)

**Pymakr version:**
v1.1.12

**Comment by jakobrosenberg** [comment]
Closing in favor of https://github.com/pycom/pymakr-vsc/issues/119
