### ISSUE TITLE
I get an error code like that 'command pymakr.connect' not found'

### ISSUE THREAD

**Issue by thatoneprogram** [pycom/pymakr-vsc#159]
how can I fix it

**Comment by thatoneprogram** [comment]
help please

**Comment by jakobrosenberg** [comment]
Hi @thatoneprogram, which version of Pymakr are you using?

**Comment by thatoneprogram** [comment]
v1.1.13

**Comment by thatoneprogram** [comment]
It is the latest version

**Comment by thatoneprogram** [comment]
WHAT CAN I DO?

**Comment by thatoneprogram** [comment]
help please

**Comment by jakobrosenberg** [comment]
@thatoneprogram please don't spam the issue. You can try the lastest beta, but if that doesn't work, I'll need more information to help you.

https://github.com/pycom/pymakr-vsc/releases/tag/v1.1.14-beta.0

**Comment by thatoneprogram** [comment]
sorry ,I needed a quick answer (cuz I am participating in Teknofest)
BUt It worked thank you!

**Comment by jakobrosenberg** [comment]
Happy you got it solved. I'll close the issue. 🙂
