### ISSUE TITLE
Pymakr on windows doesn't find micropython Serial Port

### ISSUE THREAD

**Issue by Patoche5150** [pycom/pymakr-vsc#168]
## What are the steps to reproduce this issue?
1. Update VSCode to V1.61.0
2. Update or reinstall Pymakr V1.1.14

## What happens?
Only Microsoft Serial port found with the command List Serial Ports
Impossible to open "Global Settings", nothing happen when click on the command

## What were you exvectpecting to happen?
Micropython Serial port detected by command List Serial Port and able to connect to the board

## Any logs, error output, etc? 
no specific error however if I try to connect the board even if the serial port didn't find, I have this message : JSON format error in pymakr.conf project file

## Any other comments?
The Serial port is detected by windows and works with Thonny IDE

## What versions of software are you using?

**Operating system:** Windows 10

**VSCode version:** V1.61.0

**Pymakr version:** V1.1.14

**Comment by jakobrosenberg** [comment]
Hi @Patoche5150 . Are you able to copy/paste your `pymakr.conf` here?

**Comment by Patoche5150** [comment]
Oh oh oh, pymakr.json was corrupted, only many NUL characters in the file.
I deleted it and reinstall pymakr.
After that, the pymakr.json was ok but my ESP32 Serial ports were not detected.

I added "Silicon Labs" in the "autoconnect_comport_manufacturers" list and after that, all serial ports were detected.

Unfortunatly, even if I parametered my COM serial port in the pymakr.conf, when I try to connect my board, pymakr don't use my conf file and try to connect to COM4.

Here are the differents copy/paste of my files and traces : 

pymakr.json :
`{
	"address": "192.168.4.1",
	"username": "micro",
	"password": "python",
	"sync_folder": "",
	"open_on_start": true,
	"safe_boot_on_upload": false,
	"py_ignore": [
		"pymakr.conf",
		".vscode",
		".gitignore",
		".git",
		"project.pymakr",
		"env",
		"venv"
	],
	"fast_upload": false,
	"sync_file_types": "py,txt,log,json,xml,html,js,css,mpy",
	"ctrl_c_on_connect": false,
	"sync_all_file_types": false,
	"auto_connect": true,
	"autoconnect_comport_manufacturers": [
		"Pycom",
		"Pycom Ltd.",
		"FTDI",
		"Microsoft",
		"Microchip Technology, Inc.",
		"Silicon Labs"
	]
}`

pymakr.conf :
`{
    "address": "COM5",
    "username": "micro",
    "password": "python",
    "sync_folder": "upload",
    "open_on_start": false,
    "safe_boot_on_upload": false,
    "py_ignore": [
        "pymakr.conf",
        ".vscode",
        ".gitignore",
        ".git",
        "project.pymakr",
        "env",
        "venv"
    ],
    "fast_upload": false
}`

and terminal trace with list serial ports command : 
`Found 4 serialports
COM4 (Microsoft) (copied to clipboard)
COM3 (Microsoft)
COM5 (Silicon Labs)
COM14 (Silicon Labs)`

If I try to connect the board :
`Connecting to COM4...
> Failed to connect (Error: Port is not open). Click here to try again.`

Thank you for you help, I am missing this very convenient tool !!
