### ISSUE TITLE
Plugin terminal problem

### ISSUE THREAD

**Issue by leogaggl** [pycom/pymakr-vsc#2]
Just moving this issue from the pymakr-atom repo as I created in the wrong repo.

History: [https://github.com/pycom/pymakr-atom/issues/31](https://github.com/pycom/pymakr-atom/issues/31)

Still having the problem that I can only connect via WIFI. Has anybody been able to connect to the Pycom device (in my case a LoPy) via USB Serial ?

**Comment by gmires** [comment]
hi @leogaggl ,
This way i connect you to the lopy via ssh eth.
Have you changed the configuration of pymakr plugin to make sure you do not connect to an ip address but to the serial device ??

(ex. /dev/ttyUSB0) in pymakr general option or project option.
In the box where at this time there should be the lopy ip address

see this
https://forum.pycom.io/assets/uploads/files/1502785891182-screen-shot-2017-08-15-at-4.30.28-pm.png

regards

**Comment by leogaggl** [comment]
Thanks @gmires 

"address": "/dev/ttyUSB0" in the settings file pymakr.json did the trick for me. 

Thanks for your help !
