### ISSUE TITLE
Please add Github discussions 🗣️

### ISSUE THREAD

**Issue by Josverl** [pycom/pymakr-vsc#215]
# Feature Request 🚀
https://docs.github.com/en/discussions

That would allow collaborators to share information and how-to's on making things work well.
Also this could be used to gather input for the 2.x version, and keep that separate from actual issues.

It's: 
- simple to turn on ,
- possible to move items --> discussions and vice-versa 
- can be moderated 
- create Issue can optionally redirect to start a Discussion

**Comment by jakobrosenberg** [comment]
So happy to close this issue! 🎉

https://github.com/pycom/pymakr-vsc/discussions/218
