### ISSUE TITLE
I just wanna this, but the new version prevent this.

### ISSUE THREAD

**Issue by lianggan13** [pycom/pymakr-vsc#231]
![image](https://user-images.githubusercontent.com/27114200/168331156-51857a68-0f44-42eb-9bd5-bcb0b799a955.png)

**Comment by jakobrosenberg** [comment]
Hi @lianggan13 , you can install the old version by selecting a different version.

![image](https://user-images.githubusercontent.com/4153004/168442562-b21d8ae5-af99-4cd1-8c7d-ce1270a598ad.png)


Is there a specific feature you're looking for in the new version?

**Comment by lianggan13** [comment]
Yeah，that's pretty cool!
