### ISSUE TITLE
V2, warnings are not logged properly 

### ISSUE THREAD

**Issue by Josverl** [pycom/pymakr-vsc#239]
It appears that warnings are not logged to either the output window nor to the console log.

Welke this is not a issue in itself, it may hide other issues or make them harder to understand.

**Comment by jakobrosenberg** [comment]
This is caused by a mismatch between `warning` in createLogger and `warn` in console.

Fixed this in https://github.com/pycom/pymakr-vsc/commit/7a766ca6fad72e1313600e3ffdcd4a9e2c7d38b5
