### ISSUE TITLE
UX does not always show the correct Connected/Disconnected or Running state

### ISSUE THREAD

**Issue by Josverl** [pycom/pymakr-vsc#25]
## Steps to reproduce this issue?
1. connect to a board 
2. upload and run a failing script
3.  manually reset the board 

## What happens?

* Ux still shows Connected and Running 
* when you disconnect and reconnect , the connection state is fixed , ( in 1.0.3) 
** however even then the Run state still shows running 

in other cases ( mostly when pymakr has not been able to sucesfully connect on the first attempt) the connect state always shows as disconnected [ X Pycom console ] 

## What were you expecting to happen?

at best : 
* the running and connect state to automatically detect the restart 
* the connect state to always show connected when connected 

at least : 
* the connect state to show connected after a successful re-connection 
* the run state to be stopped / reset on connect 

## What versions of software are you using?

**Operating system:**
Microsoft Windows [Version 10.0.17763.195]

**VSCode version:**
Version: 1.30.2 (user setup)
Commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
Date: 2019-01-07T22:54:13.295Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17763

**Pymakr version:**
1.0.4

**Comment by RalphHogenbirk** [comment]
@Josverl thanks for reporting. Question: are you connecting over serial or over wifi in this case? And can you post an example failing script that you use to reproduce it?

**Comment by Josverl** [comment]
@RalphHogenbirk , connecting over serial , and I now I see that I never see the connected state on my machine with the 1.0.4 release as you see below. 

![connect-disconnect-3](https://user-images.githubusercontent.com/981654/51074426-52f5aa00-167f-11e9-900f-e999328f3894.gif)

( starts connected , then disconnect , then connect again )


I think I found and solved the cause for this in : da03f9e7a5241db1bf36da903675229dfbbf3f51
but please review that

**Comment by RalphHogenbirk** [comment]
@Josverl I can't reproduce it on mac, but I can test if your commit still works? Can you tell me on which branch this fix commit (da03f9e) is on? For some reason Github doesn't tell me that.

**Comment by RalphHogenbirk** [comment]
@Josverl I've merged your latest pull request, the latest code from the 1.5 branch of pymakr-atom and your da03f9e commit to the current [develop branch.](https://github.com/pycom/pymakr-vsc/commits/develop). Still working on implementing and testing some of the new features from atom, but I'll release this soon. Let me know if this version has a working connection state on your machine!

**Comment by Josverl** [comment]
I think this is now fixed by a combo of your changed and #33
