### ISSUE TITLE
[BUG] VSCode pymakr upload fails

### ISSUE THREAD

**Issue by nznobody** [pycom/pymakr-vsc#250]
[PYCOM Forum: VSCode pymakr upload fails?](https://forum.pycom.io/topic/7589/vscode-pymakr-upload-fails?_=1654215653173)

Cross-posting here for visibility. Have not had any luck getting VSCode + Pymakr + Fipy to upload my project. Incredibly frustrating as it used to at least sometimes work in Pymakr < 2.x

**Comment by jakobrosenberg** [comment]
This should be fixed in the next patch. You can try it [here](https://marketplace.visualstudio.com/items?itemName=pycom.pymakr-preview).
