### ISSUE TITLE
[BUG] Nothing at all happens when clicking "Sync project" button on M1 Mac

### ISSUE THREAD

**Issue by VirtualWolf** [pycom/pymakr-vsc#253]
# Describe the bug
I'm able to get Pymakr to connect to my board and bring up a REPL window (though every time I disconnect or reconnect I have to press the Reset button on the board to get it to connect), but clicking the little Sync Project button does nothing whatsoever.

# Steps to reproduce
This is starting from total scratch.

1. Open a new empty window in VS Code, click the "Create project" button under Pymakr's "Projects" section:
<img width="1348" alt="1_new_project" src="https://user-images.githubusercontent.com/1644623/172040401-e63e852e-77e0-4290-9965-678d0f7389ab.png">
2. Add the serial port under the project:
<img width="413" alt="2_add_serial_port" src="https://user-images.githubusercontent.com/1644623/172040429-d982b15e-68f9-4e19-9843-0cab13109806.png">
3. Click the little lightning icon to connect and the spinner spins but never finishes:
<img width="414" alt="3_connection_spinner" src="https://user-images.githubusercontent.com/1644623/172040504-5103024b-cfff-4d2b-96b8-2f7424e1915b.png">
4. If I click the "Create terminal" icon instead, I get a message `tty.usbmodem1234561 / unknown seems to be busy. Do you wish restart it in safe mode?` Clicking the "Restart in safe mode" button does nothing, but manually pressing the reset button on the board itself then causes the terminal window to connect and I'm now at the REPL which works:
<img width="786" alt="4_repl" src="https://user-images.githubusercontent.com/1644623/172040578-a351bd59-b9a1-4a5f-85c3-a5f1b22dca0d.png">
5. Add tiny bit of code to `main.py` and click the "Sync project" button:
<img width="1348" alt="6_sync_project" src="https://user-images.githubusercontent.com/1644623/172040683-18c3d1f9-6621-46a0-8122-ecf26d87cdcd.png">

# Expected behavior
The project is uploaded and I can see the "Hello world" constantly being printed out every second in the terminal.

# Actual behaviour
Absolutely nothing happens, even when looking in the developer console with Pymakr's logs set to `debug` level.

# Environment
 - OS: macOS 12.4 on M1 Max MacBook Pro
 - Device: Unexpected Maker FeatherS2 (an ESP32S2-based board) running MicroPython 1.18.
 - VSCode: 1.67.2
 - Pymakr: 2.14.0 (preview)

# Additional context
I came across #242 and have updated the root path setting to be set to `/` for everything (I don't have any devices that don't have the root path at `/`):

```
    "pymakr.devices.config": [
    
        {
            "match": "manufacturer=.*",
            "field": "rootPath",
            "value": "/"
        }
    ],
```
But that hasn't made any difference unfortunately.

During step 3 when I initially click the lightning icon to connect but it never finishes, the debug logs show this:

```
[Extension Host] debug:  PyMakr (11913) > Device: tty.usbmodem1234561 > busy...
console.ts:137 [Extension Host] info:  PyMakr (11913) > Device: tty.usbmodem1234561 > connecting to "tty.usbmodem1234561"...
console.ts:137 [Extension Host] info:  PyMakr (11953) > Device: tty.usbmodem1234561 > Connected.
console.ts:137 [Extension Host] info:  PyMakr (11954) > Device: tty.usbmodem1234561 > Waiting for access...
console.ts:137 [Extension Host] debug:  PyMakr (11954) > stateManager > save pymakr.devices.123456 {connected: true, name: 'tty.usbmodem1234561', id: '123456', config: {…}}
console.ts:137 [Extension Host] debug:  PyMakr (11954) > stateManager > load pymakr.devices.123456 {connected: true, name: 'tty.usbmodem1234561', id: '123456', config: {…}}
console.ts:137 [Extension Host] debug:  PyMakr (11961) > Device: tty.usbmodem1234561 > idle.
console.ts:137 [Extension Host] debug:  PyMakr (11961) > Device: tty.usbmodem1234561 > busy...
console.ts:137 [Extension Host] info:  PyMakr (11961) > Device: tty.usbmodem1234561 > Got access.
console.ts:137 [Extension Host] info:  PyMakr (11961) > Device: tty.usbmodem1234561 > Getting device info.
```

Then upon pressing the reset button on the board:

```
[Extension Host] debug:  PyMakr (99785) > stateManager > save pymakr.devices.123456 {connected: false, name: 'tty.usbmodem1234561', id: '123456', config: {…}}
console.ts:137 [Extension Host] debug:  PyMakr (99786) > stateManager > load pymakr.devices.123456 {connected: false, name: 'tty.usbmodem1234561', id: '123456', config: {…}}
console.ts:137 [Extension Host] info:  PyMakr (100786) > Device: tty.usbmodem1234561 > connecting to "tty.usbmodem1234561"...
console.ts:137 [Extension Host] info:  PyMakr (100828) > Device: tty.usbmodem1234561 > Connected.
console.ts:137 [Extension Host] info:  PyMakr (100828) > Device: tty.usbmodem1234561 > Waiting for access...
console.ts:137 [Extension Host] debug:  PyMakr (100828) > stateManager > save pymakr.devices.123456 {connected: true, name: 'tty.usbmodem1234561', id: '123456', config: {…}}
console.ts:137 [Extension Host] debug:  PyMakr (100829) > stateManager > load pymakr.devices.123456 {connected: true, name: 'tty.usbmodem1234561', id: '123456', config: {…}}
console.ts:137 [Extension Host] debug:  PyMakr (100835) > Device: tty.usbmodem1234561 > idle.
console.ts:137 [Extension Host] debug:  PyMakr (100835) > Device: tty.usbmodem1234561 > busy...
console.ts:137 [Extension Host] info:  PyMakr (100835) > Device: tty.usbmodem1234561 > Got access.
console.ts:137 [Extension Host] info:  PyMakr (100835) > Device: tty.usbmodem1234561 > Getting device info.
console.ts:137 [Extension Host] debug:  PyMakr (100835) > Device: tty.usbmodem1234561 > idle.
```

But the Sync Project and and Download Project buttons do nothing. As well, the "Open device in file explorer" button briefly pops up a little thing at the bottom right saying "Adding device to explorer" and this shows in the debug logs:

```
[Extension Host] debug:  PyMakr (151257) > filesystemProvider > stat file 
{$mid: 1, external: 'serial://%252fdev%252ftty.usbmodem1234561/', path: '/', scheme: 'serial', authority: '%2Fdev%2Ftty.usbmodem1234561'}
$mid: 1
authority: "%2Fdev%2Ftty.usbmodem1234561"
external: "serial://%252fdev%252ftty.usbmodem1234561/"
path: "/"
scheme: "serial"
[[Prototype]]: Object
```
But nothing else, I'm not entirely clear on what it's *meant* to do... :)

**Comment by sinkers** [comment]
I am having pretty much exactly the same issue as this

**Comment by jakobrosenberg** [comment]
Please let me know if this fixes your issue https://github.com/pycom/pymakr-vsc/issues/242#issuecomment-1140751462.

**Comment by jakobrosenberg** [comment]
>  I'm happy to poke around and gather whatever info would be helpful for you

That would be much appreciated.

You can increase debugging level in settings:
![image](https://user-images.githubusercontent.com/4153004/172587752-8184d023-de15-443f-91b2-e8164fb25349.png)

Also, the Output tab  might contain more information
![image](https://user-images.githubusercontent.com/4153004/172587829-be14d379-0faa-4e5c-b9aa-a54523f72450.png)

And in your settings, do you have an entry like this?

```json
    "pymakr.devices.configs": [
        
        {
            "autoConnect": "lastState",
            "name": "",
            "username": "micro",
            "password": "python",
            "hidden": false,
            "rootPath": "/flash",
            "id": "Py73bb20"
        },
        {
            "autoConnect": "lastState",
            "name": "",
            "username": "micro",
            "password": "python",
            "hidden": false,
            "rootPath": "/flash",
            "id": "Py3baa06"
        }
    ]
```

If so, could you please copy paste it to here.

**Comment by VirtualWolf** [comment]
Ah yeah, the debug setting is something I stumbled onto in another issue, that's what I've had turned on with all those screenshots in my initial issue. 😄

<img width="534" alt="Screen Shot 2022-06-08 at 20 14 43 " src="https://user-images.githubusercontent.com/1644623/172592290-8c0e3a62-1b83-4e93-bdbe-4513c7aef6c2.png">

I hadn't see the Output tab before, but it's displaying all the same stuff that the developer console does anyway.

As for the settings.json, yep, it's set like this:

```
    "pymakr.devices.config": [
        {
            "match": "manufacturer=.*",
            "field": "rootPath",
            "value": "/"
        }
    ],
```

If I change `pymakr.devices.config` add an `s` at the end like in your example, it just says it's an unknown setting.

**Comment by jakobrosenberg** [comment]
Can you try Pymakr 2.15.x and see if that fixes it?

**Comment by VirtualWolf** [comment]
_Slightly_ more progress with 2.15.0 in that I get this in the Output tab:

```
debug: PyMakr (26037) > Device: tty.usbmodem1234561 > busy...
```

But nothing else. Weirdly, when I clicked the Disconnect icon, at _that_ point I got a little VSCode dialog thing popping up saying it was uploading:

<img width="449" alt="Screen Shot 2022-06-09 at 20 16 15 " src="https://user-images.githubusercontent.com/1644623/172824310-20a0c935-351a-4521-80f1-51fcc9c4a43b.png">

**Comment by jakobrosenberg** [comment]
Did the update populate your `pymakr.devices.config`?

**Comment by jakobrosenberg** [comment]
Sorry. I meant `pymakr.devices.configs`. `2.15.0` should create a new entry.

**Comment by VirtualWolf** [comment]
Hm, no, it doesn't recognise `configs` with an `s` on the end. I deleted all of the `pymakr.*` entries from `settings.json` and uninstalled 2.15.0 entirely then reinstalled, and the default examples it recreates are under `pymakr.devices.config`, and if I change it to `configs` it's not recognised as an option:

<img width="255" alt="Screen Shot 2022-06-10 at 13 21 37 " src="https://user-images.githubusercontent.com/1644623/172983971-bca12dbf-1a5a-4982-93da-aec3e21d1e96.png">

**Comment by rand12345** [comment]
Does anyone have an alternative extension or environment for MicroPython on M1? We have a project on hold here with no functional IDE.

No connection to devices, no terminal session to the devices.

The terminal process "node '/Users/xxx/.vscode/extensions/pycom.pymakr-preview-2.16.4/src/terminal/bin/client.js'" failed to launch (exit code: 1).

![image](https://user-images.githubusercontent.com/63668759/173075044-d853883e-e137-4d27-9540-0898e409b12b.png)
![image](https://user-images.githubusercontent.com/63668759/173074687-409a8c8f-67dd-4635-8050-38afafaac57b.png)
![image](https://user-images.githubusercontent.com/63668759/173074757-b72359bb-7027-487b-a136-2c492e90b5d3.png)
![image](https://user-images.githubusercontent.com/63668759/173075365-5185983d-256b-4dbd-ad1e-856c98077607.png)


REPL is operational using screen, device is working just fine. No means in which to upload files, virtually no PyMakr options in VS Code. NodeJS is latest LTS and working.

This is some serious breaking change from older versions of PyMakr!

**Comment by jakobrosenberg** [comment]
@rand12345 you can still install v1.

@VirtualWolf there was a bug in a dependency that didn't manifest itself in my local environment. I applied a fix, but I don't have any 3rd party devices to test it with. You can try it in `v2.16.4`.

**Comment by VirtualWolf** [comment]
I'm afraid it's gone backwards now. 😂 I can't connect at all even after resetting the device, and when clicking the button to open the terminal window, I get `The terminal process failed to launch: Path to shell executable "node" does not exist.`

**Comment by jakobrosenberg** [comment]
Thanks for the update @VirtualWolf .

What version are you currently on and would it be possible for us to have a remote session over Discord? My ID is `402846333087776768`

As for the the output panel. It just logs the data, it's not able to hijack it.

**Comment by jakobrosenberg** [comment]
**UPDATE:** After a session with @VirtualWolf it seems that some 3rd party devices do not work with the `micropython-ctl` package. The REPL is not detected correctly, leaving the device in a busy state.

I'll provide a follow up when we have more info or a fix.

**Comment by VirtualWolf** [comment]
We did some more testing and it seems like the root of the problem was the default chunk size and delay between sending chunks that the `micropython-ctl` library that Pymakr relies on uses. Pymakr 2.18.2 has two new settings you can configure in `pymakr.devices.configs` for your devices, and the following worked for me with an Unexpected Maker FeatherS2:

```json
"pymakr.devices.configs": [
  {
    "autoConnect": "onLostConnection",
    "name": "FeatherS2",
    "adapterOptions": {
        "chunkDelay": 20,
        "chunkSize": 256
    },
    "rootPath": "/",
    "id": "123456"
  }
]
```

**Comment by Josverl** [comment]
do you know what are the defaults are?

**Comment by jakobrosenberg** [comment]
If I remember correctly they're 3000 and 0 for size and delay.

**Comment by VirtualWolf** [comment]
Yep: https://github.com/metachris/micropython-ctl/blob/master/src/main.ts#L725-L726

**Comment by jakobrosenberg** [comment]
I assume this was fixed with the added `adapterOptions`. If not we can reopen it.

**Comment by VirtualWolf** [comment]
Ah sorry. Yes indeed, everything's working a treat now, thanks!

**Comment by Davocrack** [comment]
Hi, I have the same problem with an esp8266, and because I'm new in this world, I have no idea on where or how to put those codes. Can anyone help me? My discord id is davionga#1156

**Comment by Josverl** [comment]
> Hi, I have the same problem with an esp8266, and because I'm new in this world, I have no idea on where or how to put those codes. Can anyone help me? My discord id is davionga#1156

best to create a new issue on this repo , if you want to save typing link to this one.
