### ISSUE TITLE
[BUG] Buttons are not clickable / command pymakr.createProjectPromp not found

### ISSUE THREAD

**Issue by jairov96** [pycom/pymakr-vsc#272]
**Describe the bug**
Just installed pymakr today on both a windows device and a mac (m1 pro) device and realized all the buttons don't do anything.

When trying to use the commands through the "f1"  menu, I get this error. Same error both on mac and windows.

**To Reproduce**
1. Clock "f1"  in your keyboard
2. type "PyMakr: Create new project" 
3. Click on the first option

**Expected behavior**
The prompt to create project to work

**Screenshots**
![image](https://user-images.githubusercontent.com/9210037/182907584-bb889337-7a15-4e40-ac61-65bcecb0bec2.png)

**Desktop (please complete the following information):**
 - OS: win10 / Mac Os 10 M1 pro
 - Device ESP32 wroom
 - Pymakr Latest available as of 04/08/2022

**Comment by jakobrosenberg** [comment]
Thanks for reporting this @jairov96 . I'll try get a fix out ASAP.

**Comment by jakobrosenberg** [comment]
I was unable to replicate this locally. Do you by any chance have both Pymakr and Pymakr Preview installed? This could mess up the install of either.

**Comment by jairov96** [comment]
Hello @jakobrosenberg 

Turns out it's required to have Node.js installed for this to work and I wasn't aware of it. As soon as I installed, it's working like a charm. Huge thanks to everybody involved in this fantastic project.

Maybe would be worth pointing it out in the description that Node.js is indeed required to have this running.


Regards!

**Comment by jakobrosenberg** [comment]
This is very interesting. Node should not be required for Pymakr.

Thanks so much for the kind words.

**Comment by jairov96** [comment]
Just to point out the source where I got that:
https://randomnerdtutorials.com/micropython-esp32-esp8266-vs-code-pymakr/

At least, it solved my problems!
