### ISSUE TITLE
[BUG] uploadProject does not work

### ISSUE THREAD

**Issue by VitorNilson** [pycom/pymakr-vsc#274]
I am trying to upload a sample project to my ESP8266 board and Pymakr can not upload the project.

This is the error:
![image](https://user-images.githubusercontent.com/63609321/184540092-e66153fe-aafe-4a17-8671-9b3378075813.png)

As you can see bellow, I can access the board and run python codes on the terminal:

![image](https://user-images.githubusercontent.com/63609321/184540137-5efed69f-9a36-440c-a3db-218945cf6fbc.png)

1. Erase board and install latest micropython bin to ESP8266
2. Install Pymakr on VSCODE and crate a new project
3. Try to Sync project to device
![image](https://user-images.githubusercontent.com/63609321/184540220-83f9d29d-2744-452e-bf60-2be4d1398c8d.png)
5. See error

**Expected behavior**
Should upload code to the board.

**Desktop (please complete the following information):**
 - OS: Windows 11 64x
 - Device ESP8266
 - Pymakr v2.22.4

**Additional context**
This is the source code that I am trying to upload to the device:

![image](https://user-images.githubusercontent.com/63609321/184540389-577a4fbf-02b0-4448-b11e-817f6c07815d.png)
![image](https://user-images.githubusercontent.com/63609321/184540426-f5d68557-d266-46fd-af68-96c50a179cb4.png)
![image](https://user-images.githubusercontent.com/63609321/184540403-48867a36-4791-4bdd-b2d1-85ab7f001235.png)

**Comment by jakobrosenberg** [comment]
Hi @VitorNilson . It looks like Pymakr is trying to clear your rootPath, which I assume is ('/').

Could you try this in paste mode in your REPL and report the results to me?
```python
def rmdir(directory):
    os.chdir(directory)
    for f in os.listdir():
        try:
            os.remove(f)
        except OSError:
            pass
    for f in os.listdir():
        rmdir(f)
    os.chdir('..')
    try:
      os.rmdir(directory)
    except OSError:
      pass

# Your root dir. Please change if this is different.
rmdir('/')
```
