### ISSUE TITLE
[BUG] Cannot Reliably Sync Project to Hardware

### ISSUE THREAD

**Issue by scath999** [pycom/pymakr-vsc#278]
**Describe the bug**
Using the "Sync Project to Device" button causes only some of my files to be uploaded to the device, not all. The process will randomly freeze on one of my files (it usually isn't the same file twice, even when I've made no changes). 

This problem persists after I reset the board firmware using Pycom's firmware upgrade tool.

**To Reproduce**

1. Create a project for the GPy
2. Add multiple files to this project - currently, I'm at 9
3. Go to the Pymakr extension
4. Click "sync project to device"
5. Hard Reset the device SINCE THERE IS NO WAY TO JUST RUN THE CODE AND THE "HELP" AVAILABLE TO PUT THE DEVICE INTO "DEV" MODE DOESN'T WORK.
6. Notice that some change needs to be made
7. Make said changes 
8. Go to the Pymakr extension
9. Click "sync project to device"
10. Notice the progress dialog freezes
11. Notice also that restarting the procedure causes old, frozen "Uploading _____ to ______" notifications to remain in the bottom left of the VS Code window.

 

**Expected behavior**
1. The file upload should complete without hanging.
2. Notification boxes should disappear

**Screenshots**

Example Screenshot: Notice 

1) A notification from my previous attempt to sync my project remains ('Uploading "pymakr.conf" to "GPy/unknown"...')
2) A new notification from my current attempt to sync shows - this is frozen and never proceeds. 
3) The new notification is stuck on a different file, despite no changes to file contents being made between attempts
4) The feedback in the Developer Console of VS Code offers no insight into the issue.

![image](https://user-images.githubusercontent.com/38800373/191547958-3ce52f3d-7001-4f01-a742-fae1d5a2a80e.png)

**Desktop (please complete the following information):**

- OS: Win 10 X64
- Device GPy, Expansion Board 2.0
- Pymakr 2.22.5

**Additional context**
The old version of Pymakr was clunky and ugly af - but at least it worked. Could you please consider making version 1 available again and actually supporting it? This version SUUUUUUUUUUUUUUUUUUCKS.

**Comment by jakobrosenberg** [comment]
@scath999 v1 is still available. Both in the VSCode store and on [this branch](https://github.com/pycom/pymakr-vsc/tree/1.x).

The 3rd party controller we use to communicate with the devices unfortunately have a few device-state related bugs that manifest for some users. I was working on a new controller to address this. Alas PYCOM is currently [in administration](https://pycom.io/) and as such I can no longer access the repos.

At best I can offer my free time to provide support and feedback.

**Comment by scath999** [comment]
Hi @jakobrosenberg 

I did see that Pycom is in administration. Sorry to have hit you quite so hard in that bug report - I shouldn't have. Please accept my apology.

The issues discussed don't happen nearly as often using the [mpremote project ](https://github.com/micropython/micropython/tree/master/tools/mpremote)- I'm sure you've heard of it. If you were to work on something similar moving forward, perhaps looking at that package's code? I understand you've probably moved on, but maybe useful in the future?

I wish you the best of luck, and again apologize for letting my frustration boil over - that's on me.
