### ISSUE TITLE
Pymakr does not work on VSCode x64 on Windows

### ISSUE THREAD

**Issue by psotres** [pycom/pymakr-vsc#3]
Console shows:

Activating extension `pycom.Pymakr` failed: %1 is not a valid Win32 application.
\\?\C:\Users\myuser\.vscode\extensions\pycom.pymakr-0.1.1\precompiles\serialport-win32\build\Release\serialport.node

However it is working on VSCode x32.

**Comment by ditochino** [comment]
I fixed this issue by downloading the serialport package via npm and pasting it into the pymakr extension:

https://www.npmjs.com/package/serialport

**Comment by RalphHogenbirk** [comment]
Are you using the x64 version of VSCode as well, or the 32bit version? Turns out the plugin doesn't handle the 64 install of vscode. We'll publish a new version this week with support for it.

**Comment by RalphHogenbirk** [comment]
This has been fixed on friday, and today there was an update to support 1.16 as well on the other OS's. Let me know if this issue can be closed.
