### ISSUE TITLE
remove unneeded files from package

### ISSUE THREAD

**Issue by Josverl** [pycom/pymakr-vsc#31]
# Feature Request 🚀

## The Pymakr add-in is slow to install and contains unneeded files (likely related) 
( observed on windows , not sure on other platforms) 
The package has a lot of unneeded build , documentation and source files included.
There is a lot of room that can be won by not including these

I addition the installation and startup seem to go significantly quicker  if the /src folder is not included.
I have not timed this , but anecdotally sometimes Pymakr install can take 10-15 minutes , and it is down to <30 seconds with a reduced package ( but then I had excluded too much , so need to find the optimum ) 

However it is not quite clear (to me) which files to include / exclude from the packaging process.
Include: 
* /lib 
* package files 
* only the needed filles for serial connection / terminal 

Exclude: 
* /Src 
* Documentation  files 
* unneeded/redundant copies of serial lib 

## use .vscodeignore to reduce the package size and reduce installation time

use `.vscodeignore` to exclude the unneeded files and folders 

```
.vscode/**
.vscode-test/**
test/**
src/**
.gitignore
jsconfig.json
vsc-extension-quickstart.md
.eslintrc.json

```

but I have not been able to find the optimum as I do not quite understand the loading strategy for the serial / terminal.

## reference : https://vscode-docs.readthedocs.io/en/latest/tools/vscecli/

.vscodeignore
You can create a .vscodeignore file to exclude some files from being included in your extension's package. This file is a collection of glob patterns, one per line.
For example:
```
**/*.ts
**/tsconfig.json
!file.ts

```
You should ignore all files not needed at runtime. For example, if your extension is written in TypeScript, you should ignore all **/*.ts files, like in the previous example.
Note: Development dependencies listed in devDependencies will be automatically ignored, you don't need to add them to the .vscodeignore file.

just noticed that 'vsce package' also throws a warning : 

```
C:\develop\pymakr-vsc>vsce package
This extension consists of 5923 separate files. For performance reasons, you should bundle your extension: https://aka.ms/vscode-bundle-extension
 DONE  Packaged: C:\develop\pymakr-vsc\pymakr-1.0.7.vsix (5923 files, 18.89MB)

```

**Comment by RalphHogenbirk** [comment]
Has been implemented
