### ISSUE TITLE
command 'pymakr.connect' not found

### ISSUE THREAD

**Issue by narrowtux** [pycom/pymakr-vsc#4]
VSCode updated to 1.16 today for me and now I can't execute any of the PyMakr actions any more:

![image](https://user-images.githubusercontent.com/616791/30272680-f7074eec-96f5-11e7-8bc4-54a0238818d8.png)

**Comment by narrowtux** [comment]
I saw that you released a new version for it already but I can not see if it is installed on my machine.

**Comment by RalphHogenbirk** [comment]
Hi @narrowtux, I'm fixing this issue right now to support 1.16. Expect an update end of today or tomorrow morning.

**Comment by narrowtux** [comment]
Thanks :)

**Comment by RalphHogenbirk** [comment]
Bit late, but an update is published now. Let me know if it helps.

**Comment by narrowtux** [comment]
Yeah now everything works in 1.16, thank you :)
