### ISSUE TITLE
Can't type in Pycom Console

### ISSUE THREAD

**Issue by jrhager84** [pycom/pymakr-vsc#40]
When the console connects to the board, you cannot type anything (such as help() ) 

Please advise

**Comment by RalphHogenbirk** [comment]
Are you using the Pycom expansion board? make sure you have a jumper on the TX and RX pins. Not having them causes the behaviour you describe.
If that's not it, let me know what versions of Vscode, Pymakr and which Pycom board you are using.

**Comment by RalphHogenbirk** [comment]
Closed due to inactivity. If you need any more help with this feel free to re-open
