### ISSUE TITLE
[typo] in 'All items overritten' --> 'overwritten'

### ISSUE THREAD

**Issue by Josverl** [pycom/pymakr-vsc#52]
(Hi! 👋  Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

## What are the steps to reproduce this issue?
1. Download files from the MCU 

## What happens?

Message is shown : `All items overritten`

## What were you expecting to happen?
Message to read : `All items overwritten`

**Pymakr version:**
1.1.3

**Comment by RalphHogenbirk** [comment]
Thanks for spotting this, It's been corrected in the develop codebase.
