### ISSUE TITLE
command not found with Pymakr(1.1.3) and Visual Studio Code(1.36.1)

### ISSUE THREAD

**Issue by xtrembaker** [pycom/pymakr-vsc#54]
## What are the steps to reproduce this issue?
1. Start Visual Studio Code
2. Install Pymakr plugin

## What happens?
Plugin doesn't work, I cannot see the Pymakr console, and all shortcut fail:
CTRL + SHIFT + C = command 'pymakr.connect' not found
CTRL + SHIFT + G = command 'pymakr.globalSettings' not found
...

## What were you expecting to happen?
Things used to work with previous VS Code version installed (don't know exactly which version)

## Any logs, error output, etc?
Nope (don't know where I can get some ?)

## Any other comments?
I tried to disable / enable the plugin, no chance
I tried to uninstall / install the plugin, no chance

## What versions of software are you using?

**Operating system:**
Linux ubuntu 18.04.2 LTS

**VSCode version:**
1.36.1

**Pymakr version:**
1.1.3

**Comment by Josverl** [comment]
I think this can be closed now that 1.1.5 is out
