### ISSUE TITLE
🚀Use the vscode global storage path

### ISSUE THREAD

**Issue by Josverl** [pycom/pymakr-vsc#56]
# Feature Request 🚀
Store the global settings in a recommended  location or settings file as recommended here.  
https://code.visualstudio.com/updates/v1_31#_global-storage-path

**Comment by karlTGA** [comment]
I think that would fix a bug in the Open Source Version of VS Code. On Linux the global storage path differ (`.config/Code - OSS`). So pymakr try to create the file at `.config/Code/User` and failed without an error message.

**Comment by antti-begin** [comment]
For VSCodium users. The global settings will not be created, unless you create ~/.config/Code/User directory.

**Comment by jakobrosenberg** [comment]
Thanks for posting the solution, @antti-begin. I'll consider this issue solved.
