### ISSUE TITLE
Receiving the error while installing the paymakr on atom

### ISSUE THREAD

**Issue by lodhi830** [pycom/pymakr-vsc#61]
(Hi! 👋  Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

## What happens?
I am receiving the errors that There was an error with your serial port module, paymakr will likely not work properly. ....

![Screenshot from 2019-10-12 22-38-59](https://user-images.githubusercontent.com/8866722/66710316-d134c900-ed43-11e9-96ea-ce9c7d656867.png)

## Any logs, error output, etc?
*(If it’s long, please paste to https://gist.github.com and insert the link here)*

## What versions of the software are you using?

**Operating system:** Ubuntu 18.10

**Pymakr version:**  1.4.17

**Comment by elmasria** [comment]
Hello @lodhi830, please try to remove the whole **pymakr** package, then install the latest **1.4.17**, see if that solves the issue.

**Comment by Josverl** [comment]
I assume this should be closed or moved/copied to pymaker for Atom

**Comment by pedroknup** [comment]
This issue has been fixed with the latest Pymakr Atom update.
