### ISSUE TITLE
Upload single file to board - ESP32

### ISSUE THREAD

**Issue by VASKOTechDesign** [pycom/pymakr-vsc#76]
Hello,

is there a reason why single file upload to board do not work for ESP32?  I can upload whole project sucessfully, but I cannot upload a single file.

My settings:
VS Code:
Version: 1.41.1 (user setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.16299

Pymakr: 1.1.5

Board: Lolin D32 Pro V1.0.0

Error: "Failed to write file" - this error is listed multiple times in Terminal.

**Comment by Jerremy09** [comment]
Running system: Windows 10 (64)

**Comment by fdelmotte** [comment]
> Running system: Windows 10 (64)

Hello, Do you have any feedback, I have the same issue with an ESP8266 :(

**Comment by Jerremy09** [comment]
Hello,

unfortunately not, but I found that you can run function "Update" and PYMAKR recognize changes and upload only changed files. That Is the situation with which I'm fine.

**Comment by fastovenko** [comment]
I have the same issue. Does anyone know how to fix it?
