### ISSUE TITLE
Download files from ESP32 into PC - Download Project

### ISSUE THREAD

**Issue by VASKOTechDesign** [pycom/pymakr-vsc#77]
Pymakr do not react on "Download project" 

## What are the steps to reproduce this issue?
1. Open VS Code - Pymakr Loads
2. Connect Board 
3. hit function "Download Project"

## What happens?
nothoing in terminal, no files transfered

## What were you expecting to happen?
Transfer all fles from board into selected project folder in PC

## Any logs, error output, etc?
*(If it’s long, please paste to https://gist.github.com and insert the link here)*

## What versions of software are you using?

**Operating system:**
Windows 10 (64)

**VSCode version:**
Version: 1.41.1 (user setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.16299

**Pymakr version:**
1.1.5

**Board vesrion**
Lolin D32 Pro 1.0.0

**Comment by Josverl** [comment]
hi Jan, 
ive seen this as well. the logic is currently optimized/optimistic to uploads, 
and it does not always detect new files created or present on the board. 

one way to force it to re-scan is to delete the project.pymakr file that is used for caching that information :
- connect to your board 
```
>>> import os
>>> os.listdir()
['boot.py', 'createstubs.py', 'project.pymakr', 'lib', 'stubs', 'main.py']
``` 
- now delete the **`project.pymakr`** file, and re-try your download.
```
>>> os.remove('project.pymakr')
>>>
Downloading project (main folder)...
Not safe booting, disabled in settings

Downloading from /...
Reading files from board
Found 4 new files and 66 existing files. Do you want to download these files into your project (c:\develop\MyPython\micropython-stubs - main folder), overwriting existing files?
(Use the confirmation box at the top of the screen)
```
HTH
